services:
    sonata.admin.post:
        class: Pinit\AdminBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Pinit\ProjectBundle\Entity\Project
            - ~
        calls:
            - [ setTranslationDomain, [PinitAdminBundle]]