<?php

namespace Acme\DemoBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\ProfileFormType as BaseType;
use JMS\DiExtraBundle\Annotation as DI;

/**
 * @DI\FormType
 */
class UserProfileType extends BaseType
{
    /**
     * @DI\InjectParams({
     *     "class" = @DI\Inject("%fos_user.model.user.class%")
     * })
     */
    public function __construct($class)
    {
        parent::__construct($class); // TODO: Change the autogenerated stub
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('dateOfBirth', null, [
                'widget'=> 'single_text',
                'label' => 'Date of birth',
                'format' => 'dd.MM.yyyy',
                'attr' => [
                    'class' => 'datepicker'
                ]
            ])
        ;
    }

    public function getName()
    {
        return 'acme_user_profile';
    }
}
